# Copyright (c) Meta, Inc. and its affiliates.

from service.key_management import KeyManagementService


class OneDockerRunnerService:
    """OneDocker Runner Service integration with Nitro SDK"""

    def __init__(self, kms: KeyManagementService):
        """Initialize with a provided KMS"""
        self.kms = kms

    def _get_allocator(self):
        pass

    def get_public_key(self) -> bytes:
        return self.kms.get_public_key()

    def get_attestation_document(self) -> bytes:
        """Get attestation document generated by NSM"""
        pass

    def decrypt_data(self, data: bytes) -> bytes:
        """Decrypt data"""
        pass
