# Copyright (c) Meta, Inc. and its affiliates.

from Crypto.Cipher import PKCS1_OAEP

from key_management import KeyManagementService


class OneDockerRunnerService:
    """OneDocker Runner Service integration with Nitro SDK"""

    def __init__(self, kms: KeyManagementService):
        """Initialize with a provided KMS"""
        self.kms = kms

    def _get_allocator(self):
        pass

    def get_public_key(self) -> bytes:
        return self.kms.get_public_key()

    def get_attestation_document(self) -> bytes:
        """Get attestation document generated by NSM"""
        pass

    def decrypt_data(self, data: bytes) -> bytes:
        """Decrypt data"""
        cipher = PKCS1_OAEP.new(self.kms.get_private_key())
        plaintext = cipher.decrypt(data)
        return plaintext.decode()
